<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="1" name="pytest" skipped="0" tests="5" time="0.463">
    <testcase classname="test.testAssert.TestStringMethods" file="test/testAssert.py" line="19" name="testFalse"
              time="0.020">
        <failure message="AssertionError: False is not true">self = &lt;testAssert.TestStringMethods
            testMethod=testFalse&gt;

            def testFalse(self):
            &gt; self.assertTrue(False)
            E AssertionError: False is not true

            test/testAssert.py:21: AssertionError
        </failure>
    </testcase>
    <testcase classname="test.testAssert.TestStringMethods" file="test/testAssert.py" line="22" name="testTrue"
              time="0.003"></testcase>
    <testcase classname="test.testAssert.TestStringMethods" file="test/testAssert.py" line="8" name="test_isupper"
              time="0.003"></testcase>
    <testcase classname="test.testAssert.TestStringMethods" file="test/testAssert.py" line="12" name="test_split"
              time="0.003"></testcase>
    <testcase classname="test.testAssert.TestStringMethods" file="test/testAssert.py" line="5" name="test_upper"
              time="0.003"></testcase>
</testsuite>